name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:  
      codescan_org: 'pet-store'
      codescan_project_key: 'ci-gh-test'
      codescan_token: ${{ secrets.codescan_token2 }}
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1.1.0
    - name: Install SFDX
      env:
        SFDX_AUTOUPDATE_DISABLE: false
        SFDX_USE_GENERIC_UNIX_KEYCHAIN: true
        SFDX_DOMAIN_RETRY: 300
        SFDX_PROJECT_AUTOUPDATE_DISABLE_FOR_PACKAGE_CREATE: true
        SFDX_PROJECT_AUTOUPDATE_DISABLE_FOR_PACKAGE_VERSION_CREATE: true
      run: |
        mkdir /tmp/sfdx
        wget -q https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz -O /tmp/sfdx/sfdx-linux-amd64.tar.xz
        tar xJf /tmp/sfdx/sfdx-linux-amd64.tar.xz -C /tmp/sfdx/ --strip-components 1
        /tmp/sfdx/install
 
        echo y|sfdx plugins:install sfdx-codescan-plugin
        
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch

    - name: Run Codescan On Push
      if: github.event_name == 'push'
      run: |
        sfdx codescan:run --token=$codescan_token --projectkey=$codescan_project_key --organization=$codescan_org -Dsonar.branch.name=$branch_name

    - name: Run Codescan On PR
      if: github.event_name == 'pull_request'
      env:  
        target: ${{github.base_ref}}
        branch_type: SHORT 
      run: |
        echo "**********Branch shit*************"
        branch_name=${GITHUB_REF##*/}
        echo $branch_name
        echo "***********************"
        echo ${{github.ref}}
        echo ${{github.base_ref}}
        echo ${{github.event.pull_request.title}}
        sfdx codescan:run --token=$codescan_token --projectkey=$codescan_project_key --organization=$codescan_org -Dsonar.branch.name=$branch_name -Dsonar.branch.target=$target -Dsonar.branch.type=$branch_type
          
