name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
      - master
      - feature/**

jobs:
  build:
    runs-on: ubuntu-latest
    env:  
      codescan_org: 'pet-store'
      codescan_project_key: 'ci-integrations'
      codescan_token: ${{ secrets.codescan_token }}
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1.1.0
    - name: Install SFDX
      env:
        SFDX_AUTOUPDATE_DISABLE: false
        SFDX_USE_GENERIC_UNIX_KEYCHAIN: true
        SFDX_DOMAIN_RETRY: 300
        SFDX_PROJECT_AUTOUPDATE_DISABLE_FOR_PACKAGE_CREATE: true
        SFDX_PROJECT_AUTOUPDATE_DISABLE_FOR_PACKAGE_VERSION_CREATE: true
      run: |
        wget -q https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
        mkdir sfdx
        tar xJf sfdx-linux-amd64.tar.xz -C sfdx --strip-components 1
        ./sfdx/install
        export PATH=./sfdx/$(pwd):$PATH
 
        echo y|sfdx plugins:install sfdx-codescan-plugin

    - name: Run Codescan On Push
      if: github.event_name == 'push'
      run: |
        sfdx codescan:run --token=$codescan_token --projectkey=$codescan_project_key --organization=$codescan_org 

    - name: Run Codescan On PR
      if: github.event_name == 'pull_request'
      env:  
        branch_name: ${{ github.ref }}
        target: ${{github.base_ref}}
        branch_type: SHORT 
      run: |
        sfdx codescan:run --token=$codescan_token --projectkey=$codescan_project_key --organization=$codescan_org -Dsonar.branch.name=$branch_name -Dsonar.branch.target=$target
          
